### your site title here
title: Leo Zhang
description: Senior Lecturer at Griffith University

baseurl: "" #name of GitHub repository
url: "" #custom url to be used instead of GitHub repository
email: leo.zhang@griffith.edu.au

highlighter: rouge
markdown: kramdown

# Pagination
# paginate: 4
# permalink: /blog/:year/:title/
# paginate_path: /blog/page:num/

# Social media links in footer
# facebook: "#"
# twitter: "#"
linkedin: "leo-yu-zhang-9420997b"
# github: "lcarnevale"
researchgate: "Leo-Zhang-9"
orcid: "identifier0000-0001-9330-2662"
#google_analytics: "G-V0TBR5PTVH"
#scopus: "57195963279"
google_scholar: "JK21OM0AAAAJ"
#flickr: "lorenzocarnevale"


# highlighter: rouge
# markdown: kramdown

# Tracker
analytics:

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
# collections:
#   projects:
#     output: true
#     permalink: :path/projects/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages
  - _bibliography

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank